version: '3.9'
services:
  postgres-db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: andrii
      POSTGRES_PASSWORD: kam8elio2
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: andrii.maichub@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app_net

volumes:
  local_pgdata:
  pgadmin-data:

networks:
  app_net:
